name: CD Pipeline

on:
  push:
    branches: [ main ] # Hoặc để trigger là: tags: ['v*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'technews-api'
          region: 'asia-southeast1'
          image: 'asia-southeast1-docker.pkg.dev/technews-500407/technews-repo/technews-api:${{ github.sha }}'